/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockTokensSol from "./MockTokens.sol";
export type { mockTokensSol };
export type { ICRC99Token } from "./ICRC99Token";
