/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceToken } from "./GovernanceToken";
export type { MockDAI } from "./MockDAI";
export type { MockUSDC } from "./MockUSDC";
export type { MockUSDT } from "./MockUSDT";
