/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockTokensSol from "./MockTokens.sol";
export { ICRC99Token__factory } from "./ICRC99Token__factory";
